spring:
  datasource:
    driverClassName : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

      bindings:
        input:
          destination: msqueue




security:
  basic:
    enabled: false
